/**
 * Clinical Assessment Report Component
 * 
 * Displays assessment results in 5 core sections:
 * 1. Patient Assessment (Diagnosis, Etiology, Urgency)
 * 2. Management Plan
 * 3. Antibiotic Considerations
 * 4. Follow-up Schedule
 * 5. Patient Counseling
 */

import React, {useState} from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
} from 'react-native';
import Markdown from 'react-native-markdown-display';
import {CaseAssessment, UrgencyLevel} from '../../types';

interface AssessmentReportProps {
  assessment: CaseAssessment;
}

interface SectionProps {
  title: string;
  icon: string;
  children: React.ReactNode;
  isExpanded: boolean;
  onToggle: () => void;
}

const Section: React.FC<SectionProps> = ({
  title,
  icon,
  children,
  isExpanded,
  onToggle,
}) => {
  return (
    <View style={styles.section}>
      <TouchableOpacity style={styles.sectionHeader} onPress={onToggle}>
        <View style={styles.sectionHeaderLeft}>
          <Text style={styles.sectionIcon}>{icon}</Text>
          <Text style={styles.sectionTitle}>{title}</Text>
        </View>
        <Text style={styles.sectionToggle}>{isExpanded ? '▼' : '▶'}</Text>
      </TouchableOpacity>
      {isExpanded && <View style={styles.sectionContent}>{children}</View>}
    </View>
  );
};

export const AssessmentReport: React.FC<AssessmentReportProps> = ({
  assessment,
}) => {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(['assessment', 'management', 'antibiotics', 'followup', 'counseling']),
  );

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  const getUrgencyColor = (urgency: UrgencyLevel) => {
    switch (urgency) {
      case 'emergency':
        return {bg: '#fee2e2', border: '#ef4444', text: '#991b1b'};
      case 'urgent':
        return {bg: '#fed7aa', border: '#f97316', text: '#9a3412'};
      case 'routine':
        return {bg: '#dbeafe', border: '#3b82f6', text: '#1e3a8a'};
      case 'home-care':
        return {bg: '#dcfce7', border: '#16a34a', text: '#14532d'};
      default:
        return {bg: '#f3f4f6', border: '#6b7280', text: '#1f2937'};
    }
  };

  const getUrgencyLabel = (urgency: UrgencyLevel) => {
    switch (urgency) {
      case 'emergency':
        return '⚠️ EMERGENCY - Immediate Care Required';
      case 'urgent':
        return '🕐 URGENT - See Dentist Within 24-48 Hours';
      case 'routine':
        return 'ℹ️ ROUTINE - Schedule Regular Appointment';
      case 'home-care':
        return '✓ HOME CARE - Self-Care with Monitoring';
      default:
        return String(urgency).toUpperCase();
    }
  };

  const urgencyColors = getUrgencyColor(assessment.urgency);

  return (
    <ScrollView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Clinical Case Assessment</Text>
        <Text style={styles.headerSubtitle}>
          Analysis generated by DentalGemma AI
        </Text>
      </View>

      {/* Urgency Banner - No blue bar or icon */}
      <View
        style={[
          styles.urgencyBanner,
          {backgroundColor: urgencyColors.bg},
        ]}>
        <Text style={[styles.urgencyTitle, {color: urgencyColors.text}]}>
          {getUrgencyLabel(assessment.urgency)}
        </Text>
        <Text style={[styles.urgencyDescription, {color: urgencyColors.text}]}>
          {assessment.urgency === 'emergency' &&
            'Seek immediate medical attention at emergency room or urgent care.'}
          {assessment.urgency === 'urgent' &&
            'Contact your dentist as soon as possible for an appointment.'}
          {assessment.urgency === 'routine' &&
            'Schedule a regular dental appointment at your convenience.'}
          {assessment.urgency === 'home-care' &&
            'Follow home care instructions and monitor symptoms.'}
        </Text>
      </View>

      {/* Section 1: Patient Assessment */}
      <Section
        title="1. Patient Assessment"
        icon="✓"
        isExpanded={expandedSections.has('assessment')}
        onToggle={() => toggleSection('assessment')}>
        <View style={styles.subsection}>
          <Text style={styles.subsectionTitle}>Primary Diagnosis</Text>
          <View style={styles.diagnosisBox}>
            <Markdown style={markdownStyles}>
              {assessment.diagnosis.primary}
            </Markdown>
          </View>
        </View>

        {assessment.diagnosis.differential.length > 0 && (
          <View style={styles.subsection}>
            <Text style={styles.subsectionTitle}>Differential Diagnoses</Text>
            {assessment.diagnosis.differential.map((diff, index) => (
              <View key={index} style={styles.listItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.listItemText}>{diff}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={styles.subsection}>
          <Text style={styles.subsectionTitle}>Etiology / Root Cause</Text>
          <Text style={styles.bodyText}>{assessment.etiology.rootCause}</Text>
        </View>
      </Section>

      {/* Section 2: Management Plan */}
      <Section
        title="2. Management Plan"
        icon="🕐"
        isExpanded={expandedSections.has('management')}
        onToggle={() => toggleSection('management')}>
        <View style={styles.subsection}>
          <Text style={styles.subsectionTitle}>
            Recommended Treatment Protocol
          </Text>
          {assessment.managementPlan.protocol.map((step, index) => (
            <View key={index} style={styles.protocolStep}>
              <View style={styles.stepNumber}>
                <Text style={styles.stepNumberText}>{index + 1}</Text>
              </View>
              <Text style={styles.stepText}>{step}</Text>
            </View>
          ))}
        </View>
      </Section>

      {/* Section 3: Antibiotics */}
      <Section
        title="3. Antibiotic Considerations"
        icon="💊"
        isExpanded={expandedSections.has('antibiotics')}
        onToggle={() => toggleSection('antibiotics')}>
        <View
          style={[
            styles.antibioticBadge,
            assessment.antibiotics?.indicated
              ? styles.antibioticBadgeYes
              : styles.antibioticBadgeNo,
          ]}>
          <Text style={styles.antibioticBadgeIcon}>
            {assessment.antibiotics?.indicated ? '⚠️' : '✓'}
          </Text>
          <Text style={styles.antibioticBadgeText}>
            Antibiotics Indicated:{' '}
            {assessment.antibiotics?.indicated ? 'YES' : 'NO'}
          </Text>
        </View>

        <View style={styles.subsection}>
          <Text style={styles.subsectionTitle}>Reasoning</Text>
          <Text style={styles.bodyText}>
            {assessment.antibiotics?.reason ||
              'No specific clinical indication for antibiotics at this time.'}
          </Text>
        </View>
      </Section>

      {/* Section 4: Follow-up */}
      <Section
        title="4. Follow-up Schedule"
        icon="🕐"
        isExpanded={expandedSections.has('followup')}
        onToggle={() => toggleSection('followup')}>
        <View style={styles.subsection}>
          <Text style={styles.subsectionTitle}>Timing</Text>
          <Text style={styles.timingText}>{assessment.followUp.timing}</Text>
        </View>

        {assessment.followUp.monitoring.length > 0 && (
          <View style={styles.subsection}>
            <Text style={styles.subsectionTitle}>Monitoring Parameters</Text>
            {assessment.followUp.monitoring.map((param, index) => (
              <View key={index} style={styles.listItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.listItemText}>{param}</Text>
              </View>
            ))}
          </View>
        )}
      </Section>

      {/* Section 5: Patient Counseling */}
      <Section
        title="5. Patient Counseling"
        icon="ℹ️"
        isExpanded={expandedSections.has('counseling')}
        onToggle={() => toggleSection('counseling')}>
        <View style={styles.counselingBox}>
          <Text style={styles.subsectionTitle}>
            Patient-Friendly Explanation
          </Text>
          <Text style={styles.bodyText}>
            {assessment.patientCounseling.explanation}
          </Text>
        </View>
      </Section>

      {/* Medical Disclaimer */}
      <View style={styles.disclaimer}>
        <Text style={styles.disclaimerTitle}>⚠️ Medical Disclaimer</Text>
        <Text style={styles.disclaimerText}>
          This AI-powered assessment is for educational and informational
          purposes only. It does not constitute medical advice, diagnosis, or
          treatment. Always seek the advice of qualified healthcare providers
          with any questions regarding medical conditions.
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  header: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#6b7280',
  },
  urgencyBanner: {
    margin: 16,
    padding: 16,
    borderRadius: 8,
  },
  urgencyTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
  },
  urgencyDescription: {
    fontSize: 14,
  },
  section: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#f9fafb',
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  sectionIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    flex: 1,
  },
  sectionToggle: {
    fontSize: 14,
    color: '#6b7280',
  },
  sectionContent: {
    padding: 16,
  },
  subsection: {
    marginBottom: 16,
  },
  subsectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  diagnosisBox: {
    backgroundColor: '#eff6ff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bullet: {
    fontSize: 14,
    color: '#6b7280',
    marginRight: 8,
    marginTop: 2,
  },
  listItemText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  bodyText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  protocolStep: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 8,
  },
  stepNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  stepNumberText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1e40af',
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  antibioticBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
  },
  antibioticBadgeYes: {
    backgroundColor: '#fef3c7',
    borderColor: '#fbbf24',
  },
  antibioticBadgeNo: {
    backgroundColor: '#dcfce7',
    borderColor: '#16a34a',
  },
  antibioticBadgeIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  antibioticBadgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  timingText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  counselingBox: {
    backgroundColor: '#f9fafb',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  disclaimer: {
    margin: 16,
    padding: 16,
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
  },
  disclaimerTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  disclaimerText: {
    fontSize: 12,
    color: '#374151',
    lineHeight: 18,
  },
});

const markdownStyles = StyleSheet.create({
  body: {
    fontSize: 14,
    color: '#111827',
    lineHeight: 20,
  },
  heading1: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginTop: 12,
    marginBottom: 6,
  },
  heading2: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginTop: 10,
    marginBottom: 4,
  },
  heading3: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginTop: 8,
    marginBottom: 4,
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 8,
    fontSize: 14,
    color: '#111827',
    lineHeight: 20,
  },
  strong: {
    fontWeight: '700',
    color: '#111827',
  },
  em: {
    fontStyle: 'italic',
  },
  bullet_list: {
    marginBottom: 8,
  },
  ordered_list: {
    marginBottom: 8,
  },
  list_item: {
    marginBottom: 4,
    fontSize: 14,
    color: '#111827',
    lineHeight: 20,
  },
});
