'use client';

/**
 * Simplified Clinical Assessment Report Component
 * 
 * Displays simplified assessment results in 5 core sections:
 * 1. Patient Assessment (Diagnosis, Etiology, Urgency)
 * 2. Management Plan (Step-by-step protocol)
 * 3. Antibiotic Considerations (Indicated/Not Indicated + Reason)
 * 4. Follow-up Schedule (Timing + Monitoring)
 * 5. Patient Counseling (Patient-friendly explanation)
 */

import { useState } from 'react';
import { ChevronDown, ChevronUp, AlertTriangle, Clock, CheckCircle, Info, Pill } from 'lucide-react';
import { MarkdownRenderer } from '@/components/shared/markdown-renderer';
import type { CaseAssessment, UrgencyLevel } from '@/types';

interface AssessmentReportProps {
  assessment: CaseAssessment;
  onExport?: () => void;
}

interface SectionProps {
  id: string;
  title: string;
  icon: any;
  children: React.ReactNode;
  isExpanded: boolean;
  onToggle: (id: string) => void;
}

const Section = ({ 
  id, 
  title, 
  icon: Icon,
  children,
  isExpanded,
  onToggle
}: SectionProps) => {
  return (
    <div className="border rounded-lg shadow-sm overflow-hidden mb-4 bg-white">
      <button
        type="button"
        onClick={() => onToggle(id)}
        className="w-full px-6 py-4 bg-gray-50/50 hover:bg-gray-100/50 flex items-center justify-between transition-colors"
      >
        <div className="flex items-center gap-3">
          <Icon className="w-5 h-5 text-blue-600" />
          <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
        </div>
        {isExpanded ? (
          <ChevronUp className="w-5 h-5 text-gray-600" />
        ) : (
          <ChevronDown className="w-5 h-5 text-gray-600" />
        )}
      </button>
      {isExpanded && (
        <div className="px-6 py-4">
          {children}
        </div>
      )}
    </div>
  );
};

export function AssessmentReport({ assessment, onExport }: AssessmentReportProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(['assessment', 'management', 'antibiotics', 'followup', 'counseling'])
  );

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  // Urgency color mapping
  const getUrgencyColor = (urgency: UrgencyLevel) => {
    switch (urgency) {
      case 'emergency':
        return 'bg-red-100 border-red-500 text-red-900';
      case 'urgent':
        return 'bg-orange-100 border-orange-500 text-orange-900';
      case 'routine':
        return 'bg-blue-100 border-blue-500 text-blue-900';
      case 'home-care':
        return 'bg-green-100 border-green-500 text-green-900';
      default:
        return 'bg-gray-100 border-gray-500 text-gray-900';
    }
  };

  const getUrgencyIcon = (urgency: UrgencyLevel) => {
    switch (urgency) {
      case 'emergency':
        return <AlertTriangle className="w-5 h-5" />;
      case 'urgent':
        return <Clock className="w-5 h-5" />;
      case 'routine':
        return <Info className="w-5 h-5" />;
      case 'home-care':
        return <CheckCircle className="w-5 h-5" />;
      default:
        return <Info className="w-5 h-5" />;
    }
  };

  const getUrgencyLabel = (urgency: UrgencyLevel) => {
    switch (urgency) {
      case 'emergency':
        return 'EMERGENCY - Immediate Care Required';
      case 'urgent':
        return 'URGENT - See Dentist Within 24-48 Hours';
      case 'routine':
        return 'ROUTINE - Schedule Regular Appointment';
      case 'home-care':
        return 'HOME CARE - Self-Care with Monitoring';
      default:
        return String(urgency).toUpperCase();
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto pb-10">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-3xl font-bold text-gray-900">Clinical Case Assessment</h2>
          {onExport && (
            <button
              type="button"
              onClick={onExport}
              className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
            >
              Export PDF
            </button>
          )}
        </div>
        <p className="text-sm text-gray-600">
          Analysis generated by DentalGemma AI
        </p>
      </div>

      {/* Urgency Banner */}
      <div className={`rounded-lg border-l-4 p-6 mb-6 shadow-sm ${getUrgencyColor(assessment.urgency)}`}>
        <div className="flex items-center gap-3">
          {getUrgencyIcon(assessment.urgency)}
          <div>
            <h3 className="text-xl font-bold">{getUrgencyLabel(assessment.urgency)}</h3>
            <p className="text-sm mt-1">
              {assessment.urgency === 'emergency' && 'Seek immediate medical attention at emergency room or urgent care.'}
              {assessment.urgency === 'urgent' && 'Contact your dentist as soon as possible for an appointment.'}
              {assessment.urgency === 'routine' && 'Schedule a regular dental appointment at your convenience.'}
              {assessment.urgency === 'home-care' && 'Follow home care instructions and monitor symptoms.'}
            </p>
          </div>
        </div>
      </div>

      {/* Section 1: Patient Assessment */}
      <Section 
        id="assessment" 
        title="1. Patient Assessment" 
        icon={CheckCircle}
        isExpanded={expandedSections.has('assessment')}
        onToggle={toggleSection}
      >
        <div className="space-y-6">
          <div>
            <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Primary Diagnosis</h4>
            <div className="bg-blue-50/50 p-4 rounded-lg border border-blue-100">
              <MarkdownRenderer content={assessment.diagnosis.primary} className="text-gray-900 font-medium" />
            </div>
          </div>

          {assessment.diagnosis.differential.length > 0 && (
            <div>
              <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Differential Diagnoses</h4>
              <ul className="space-y-2">
                {assessment.diagnosis.differential.map((diff, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm text-gray-700">
                    <span className="text-gray-400 mt-1">•</span>
                    <MarkdownRenderer content={diff} />
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div>
            <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Etiology / Root Cause</h4>
            <MarkdownRenderer content={assessment.etiology.rootCause} className="text-gray-700 text-sm leading-relaxed" />
          </div>
        </div>
      </Section>

      {/* Section 2: Management Plan */}
      <Section 
        id="management" 
        title="2. Management Plan" 
        icon={Clock}
        isExpanded={expandedSections.has('management')}
        onToggle={toggleSection}
      >
        <div className="space-y-4">
          <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Recommended Treatment Protocol</h4>
          <div className="space-y-3">
            {assessment.managementPlan.protocol.map((step, index) => (
              <div key={index} className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg border border-gray-100">
                <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-blue-100 text-blue-700 rounded-full text-xs font-bold">
                  {index + 1}
                </span>
                <MarkdownRenderer content={step} className="text-gray-700 text-sm" />
              </div>
            ))}
          </div>
        </div>
      </Section>

      {/* Section 3: Antibiotics */}
      <Section 
        id="antibiotics" 
        title="3. Antibiotic Considerations" 
        icon={Pill}
        isExpanded={expandedSections.has('antibiotics')}
        onToggle={toggleSection}
      >
        <div className="space-y-4">
          <div className={`p-4 rounded-lg border flex items-center gap-3 ${assessment.antibiotics?.indicated ? 'bg-amber-50 border-amber-200' : 'bg-green-50 border-green-200'}`}>
            {assessment.antibiotics?.indicated ? (
              <AlertTriangle className="w-5 h-5 text-amber-600" />
            ) : (
              <CheckCircle className="w-5 h-5 text-green-600" />
            )}
            <span className="font-semibold text-gray-900">
              Antibiotics Indicated: {assessment.antibiotics?.indicated ? 'YES' : 'NO'}
            </span>
          </div>
          
          <div>
            <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Reasoning</h4>
            <MarkdownRenderer 
              content={assessment.antibiotics?.reason || 'No specific clinical indication for antibiotics at this time.'} 
              className="text-gray-700 text-sm" 
            />
          </div>
        </div>
      </Section>

      {/* Section 4: Follow-up */}
      <Section 
        id="followup" 
        title="4. Follow-up Schedule" 
        icon={Clock}
        isExpanded={expandedSections.has('followup')}
        onToggle={toggleSection}
      >
        <div className="space-y-4">
          <div>
            <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-1">Timing</h4>
            <p className="text-gray-900 font-medium">{assessment.followUp.timing}</p>
          </div>

          {assessment.followUp.monitoring.length > 0 && (
            <div>
              <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Monitoring Parameters</h4>
              <ul className="space-y-2">
                {assessment.followUp.monitoring.map((param, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm text-gray-700">
                    <span className="text-blue-500 mt-1.5">•</span>
                    <MarkdownRenderer content={param} />
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </Section>

      {/* Section 5: Patient Counseling */}
      <Section 
        id="counseling" 
        title="5. Patient Counseling" 
        icon={Info}
        isExpanded={expandedSections.has('counseling')}
        onToggle={toggleSection}
      >
        <div className="p-4 bg-gray-50 rounded-lg border border-gray-100">
          <h4 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Patient-Friendly Explanation</h4>
          <MarkdownRenderer content={assessment.patientCounseling.explanation} className="text-gray-700 text-sm leading-relaxed" />
        </div>
      </Section>
    </div>
  );
}
